install:
  - touch /test-install-all # test
  - npm install
script:
  - npm test
docker:
  socketPath: /var/run/docker.sock
env:
  - TEST_ENV_ALL=true # test
targets:
  ubuntu:
    tags:
      - "16.04"
    install:
      - touch /test-install-target # test
      - apt-get update -qq
      - apt-get upgrade -y -qq
      - apt-get install nodejs nodejs-legacy npm -y -qq
    env:
      - TEST_ENV_TARGET={{name}}:{{tag}} # test
  fedora:
    tags:
      - "25"
    install:
      - touch /test-install-target # test
      - dnf update -y -q
      - dnf install node npm -y -q
    env:
      - TEST_ENV_TARGET={{name}}:{{tag}} # test
