install:
  - npm install
script:
  - npm test
docker:
  socketPath: /var/run/docker.sock
targets:
  ubuntu:
    tags:
      - "14.04"
      - "15.10"
    install:
      - apt-get update -qq
      - apt-get upgrade -y -qq
      - apt-get install nodejs nodejs-legacy npm -y -qq
  fedora:
    tags:
      - "22"
      - "23"
    install:
      - dnf update -y -q
      - dnf install node npm -y -q
