language: node_js
sudo: required
services:
  - docker
script:
  - node chimera.js --verbose
env:
  matrix:
    - CHIMERA_TARGET=ubuntu:14.04
    - CHIMERA_TARGET=ubuntu:15.10
    - CHIMERA_TARGET=fedora
